"""Constants used in the preprocessing and training scripts."""

SEP_TOKEN = "<sep>"

ALL_CATEGORIES_WITHOUT_NAMES = set(
    [
        ".NET",
        "1C",
        "ALT Linux",
        "ALTLinux на Эльбрусе",
        "AR",
        "AWS",
        "Accessibility",
        "Agile",
        "Agile Introduction",
        "Agile process",
        "Agile в корпорациях",
        "Agile — технологические практики",
        "Agile&Lean Mindset",
        "Agile-культура",
        "Agile-масштабирование",
        "Agile-преобразования",
        "Alfresco",
        "Ansible",
        "Arduino",
        "AstraLinux",
        "Atlassian",
        "Azure",
        "B2B продукты",
        "BDD",
        "BigData",
        "Blockchain",
        "Bluemix",
        "Business rules engine",
        "C++",
        "CMMI",
        "CQRS",
        "CRIU",
        "Clouds",
        "Clsync",
        "Code Review",
        "Collaboration tools",
        "Configuration Management",
        "ContactOK",
        "Continuous Integration",
        "CouchDB",
        "Csharp",
        "CustisWikiToLib",
        "Customer Journey Map",
        "DDD",
        "DSL-языки",
        "Data Analysis",
        "Deployment",
        "Design Thinking",
        "DevOps",
        "Draft",
        "E-commerce",
        "Embox",
        "Erlang",
        "Extreme Programming",
        "Feature Branches",
        "Firefox",
        "Foresight management",
        "FreeIPA",
        "Front end development",
        "Fsharp",
        "GWT",
        "Glibc",
        "Go",
        "Groovy",
        "Growth Hacking",
        "HR",
        "Hardware",
        "Health",
        "High Performace Computing",
        "Highload-архитектуры",
        "IP-телефония",
        "IT-законы",
        "IT-образование",
        "Impact Map",
        "Information Security",
        "Internet of Thing",
        "Java",
        "Java EE",
        "Javascript",
        "Jenkins",
        "Kanban",
        "Knowledge Management",
        "Kotlin",
        "Kubernetes",
        "LAMP",
        "LSM",
        "LeSS",
        "Lean",
        "Lean Startup",
        "Legacy",
        "Libreoffice",
        "Linux",
        "Linux для Эльбруса",
        "Linux-дистрибутивы",
        "Linux-дистрибутивы для Enterprise",
        "Linux-обучение",
        "Lua",
        "MIPS",
        "Machine Learning",
        "Mechanics",
        "Microsoft",
        "Misc",
        "Mkimage-profiles",
        "MongoDB",
        "Morpheus",
        "MySQL",
        "NLP",
        "NOSQL",
        "NUI",
        "Natural Language Processing",
        "NeedContacts",
        "Nemerle",
        "Node.js",
        "Object Oriented Programming",
        "Open-source",
        "Open-source CAD",
        "Open-source CMS",
        "Open-source CRM",
        "Open-source ERP",
        "Open-source PAAS",
        "Open-source TCO",
        "Open-source and Community",
        "Open-source and hardware",
        "Open-source communications",
        "Open-source for Enterprise",
        "Open-source operating systems",
        "Open-source projects",
        "Open-source СУБД",
        "Open-source и законы",
        "OpenShift",
        "OpenStack",
        "OpenVZ",
        "PAAS",
        "PHP",
        "Pascale Xelot-Dugat",
        "People Management",
        "Pivot",
        "PostgreSQL",
        "ProductMeetup",
        "Python",
        "RISC-V",
        "ROSA Linux",
        "ROSALab",
        "RTOS",
        "Reviewed",
        "Riak",
        "Ruby",
        "RunaWFE",
        "SAP",
        "SELinux",
        "SOLID",
        "SVM",
        "Samba",
        "Scala",
        "Scrum",
        "Serverless",
        "Sharepoint",
        "SkillsWiki",
        "Skype",
        "Software Defined Networks",
        "Strace",
        "Support",
        "TAU-платформа",
        "TDD",
        "Talks in English",
        "Tarantool",
        "Taucraft",
        "Team Communication",
        "Teмы",
        "ToPublish",
        "Tuukka Ahoniemi",
        "UI",
        "UI SmartTV",
        "UI бизнес-приложений",
        "UX",
        "UX + Agile",
        "UX проектирование",
        "User Story",
        "VCS",
        "Visual Studio",
        "Waterfall",
        "WebRTC",
        "Windows",
        "World Usability Day",
        "ZFS",
        "Zabbix",
        "Автоматизированное тестирование",
        "Алгоритмы",
        "Анализ программ и систем",
        "Аналитика",
        "Архитектура",
        "Архитектура информационных систем",
        "Архитектура серверных приложений",
        "Аутентификация и авторизация",
        "БПЛА",
        "Базы данных",
        "Байкал",
        "Безопасность",
        "Бизнес в IT",
        "Бизнес и СПО",
        "Бизнес-анализ",
        "Блиц-доклады",
        "Веб-дизайн",
        "Веб-разработка",
        "Вебинары PingWin",
        "Верификация",
        "Видеосвязь",
        "Визуализация",
        "Виртуализация",
        "Виртуальный ассистент",
        "Встраиваемые системы",
        "Выход на зарубежные рынки",
        "Геймификация",
        "Геймификация в UX",
        "Геолокация",
        "Голосовой интерфейс",
        "Госсектор",
        "Государство и софт",
        "Графовые базы данных",
        "Диаграммы Кано",
        "Дизайн",
        "Динамический анализ",
        "Дискуссии",
        "Дискуссии о юзабилити",
        "Доверенная загрузка",
        "Доклад со стенограммой",
        "Докладчики",
        "Доклады на английском",
        "Доклады на белорусском языке",
        "Доклады на иностранных языках",
        "Доклады на украинском",
        "Документация и Agile",
        "Документирование",
        "Запуск продукта",
        "Запуск продукта в Retail",
        "Инструменты майнтейнера",
        "Инструменты майнтейнеров",
        "Инструменты разработки",
        "Информационная безопасность",
        "Информационная безопасность и СПО",
        "Информационные системы ВУЗов",
        "Использование open-source",
        "Исследовательское тестирование",
        "История из практики",
        "Картография",
        "Карьера в IT",
        "Командообразование",
        "Компиляторы",
        "Компиляция под Linux",
        "Компьютерная графика",
        "Компьютерное зрение",
        "Конференции",
        "Корпоративные решения",
        "Криптография",
        "Кроссплатформенная разработка",
        "Круглый стол",
        "Кумир",
        "Лидерство",
        "Линейки конференций",
        "Локализация",
        "Маркетинг",
        "Мастер-классы",
        "Менеджмент",
        "Метрики качества",
        "Микропрограммирование",
        "Микросервисы",
        "Мобильная разработка",
        "Моделирование бизнес-процессов",
        "Моделирование физических систем",
        "Монетизация",
        "Мониторинг",
        "Мотивация",
        "Наука",
        "Облачные сервисы",
        "Образование",
        "Обучение",
        "Обучение бизнес-анализу",
        "Обучение бизнес-процессам",
        "Обучение проектному менеджменту",
        "Обучение системному программированию",
        "Онлайн-обучение",
        "Операционные системы",
        "Оптимизация приложения",
        "Опыт внедрения СПО",
        "Организационные изменения",
        "Организационный анализ",
        "Открытые данные",
        "Отладка",
        "Оценка сотрудников",
        "Очереди",
        "Параллельное программирование",
        "Пиктомир",
        "Планирование",
        "Планирование в Agile",
        "Планировка задач",
        "Привественные речи",
        "Программирование",
        "Программная архитектура",
        "Продуктовая аналитика",
        "Прототипирование UI",
        "Процесс разработки",
        "Процесс разработки UX и UI",
        "Процесс тестирования",
        "Психология пользователя",
        "Психология разработки",
        "Разработка open-source",
        "Разработка десктоп-приложений",
        "Разработка десктопных приложений под Windows",
        "Разработка игр",
        "Разработка операционных систем",
        "Распределенные системы",
        "Редкие языки программирования",
        "Реклама",
        "Реклама компании",
        "Рекомендательные системы",
        "Ретроспектива",
        "Рефакторинг",
        "Робототехника",
        "С++",
        "САПР",
        "СПО в Госуправлении",
        "СПО в России",
        "СПО в науке",
        "СПО в образовании",
        "СПО в творчестве",
        "СПО для системного администрирования",
        "СУБД",
        "Свободные библиотеки построения графиков",
        "Свободные лицензии",
        "Сервис-ориентированная архитектура",
        "Сети",
        "Системное администрирование",
        "Системное мышление",
        "Системный анализ",
        "Системный подход",
        "Системы управления версиями",
        "Скрытые категории",
        "Собрания ALT.NET",
        "Совещания",
        "Стажировка",
        "Статический анализ кода",
        "Стратегическое планирование",
        "ТРИЗ",
        "Темы",
        "Теория ограничений",
        "Тестирование",
        "Тестирование UI",
        "Тестирование игр",
        "Тестирование мобильных приложений",
        "Тестирование производительности",
        "Технологии",
        "Технологии будущего",
        "Технологии крупных вендоров",
        "Тренды Open-source",
        "Умные вещи",
        "Управление заинтересованными сторонами",
        "Управление качеством",
        "Управление продуктами",
        "Управление рисками",
        "Управление собой",
        "Управление техподдержкой",
        "Управление требованиями",
        "Файловые системы",
        "Философия программирования",
        "Философия юзабилити",
        "Финансовые системы",
        "Фреймворки",
        "Фриланс",
        "Функциональное программирование",
        "Хранение данных",
        "Хэши",
        "Эксплуатация",
        "Эльбрус",
        "Юзабилити",
        "Юзабилити в 1C",
        "Юзабилити в играх",
        "Юзабилити интернет-магазинов",
        "Юзабилити исследования",
        "Юзабилити мобильных устройств",
        "Юзабилити образование",
        "Юзабилити поиска",
        "Юзабилити текста",
        "Языки программирования",
    ]
)

# Define LaTeX and Markdown command substrings to filter out
LATEX_MARKDOWN_COMMANDS = [
    "begin",
    "end",
    "hline",
    "hhline",
    "multicolumn",
    "label",
    "tabular",
    "centertypical",
    "fig",
    "file",
    "pgc",
    "c37",
    "c12",
    "c2",
    "c1",
    "c0k",
    "c2hline",
    "table",
    "figure",
    "section",
    "subsection",
]

# Define common file extensions to filter out
FILE_EXTENSIONS = [
    "pdf",
    "jpg",
    "jpeg",
    "png",
    "docx",
    "xlsx",
    "bmp",
    "svg",
    "pptx",
    "txt",
    "csv",
]

ARTM_MODALITIES = ("@word", "@bigramm", "@category")
